#!/usr/bin/env bash
echo "clockette"
tmux setenv -u '@PLUG_ROOT'
tmux setenv '@PLUG_ROOT' "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PLUG_ROOT="$(tmux display -p "#{@PLUG_ROOT}")"

$PLUG_ROOT/scripts/tmux-clockette.sh
tmux bind M-c run "$PLUG_ROOT/tmux-metaphile"
